const FESTIVAL_DATA = [
  {
    name: "Primavera Sound Barcelona",
    city: "Barcelona",
    province: "Barcelona",
    subcategories: ["Indie", "Alternative", "Pop", "Rock", "Electrónica"],
    official_url: "https://www.primaverasound.com/barcelona",
  },
  {
    name: "Sónar",
    city: "L'Hospitalet de Llobregat",
    province: "Barcelona",
    subcategories: ["Electrónica", "Techno", "Experimental"],
    official_url: "https://sonar.es/",
  },
  {
    name: "Mad Cool Festival",
    city: "Madrid",
    province: "Madrid",
    subcategories: ["Rock", "Indie", "Pop", "Alternative"],
    official_url: "https://madcoolfestival.es/",
  },
  {
    name: "Bilbao BBK Live",
    city: "Bilbao",
    province: "Bizkaia",
    subcategories: ["Indie", "Rock", "Pop", "Electrónica"],
    official_url: "https://bilbaobbklive.com/",
  },
  {
    name: "Cruïlla",
    city: "Barcelona",
    province: "Barcelona",
    subcategories: ["Pop", "Indie", "Rock", "Urbana", "Electrónica"],
    official_url: "https://www.cruillabarcelona.com/",
  },
  {
    name: "FIB Benicàssim",
    city: "Benicàssim",
    province: "Castellón",
    subcategories: ["Indie", "Pop", "Rock", "Electrónica"],
    official_url: "https://fiberfib.com/",
  },
  {
    name: "Arenal Sound",
    city: "Burriana",
    province: "Castellón",
    subcategories: ["Pop", "Urbana", "Electrónica", "Indie"],
    official_url: "https://arenalsound.com/",
    status: "confirmed",
  },
  {
    name: "Resurrection Fest",
    city: "Viveiro",
    province: "Lugo",
    subcategories: ["Metal", "Hardcore", "Rock", "Punk"],
    official_url: "https://www.resurrectionfest.es/",
  },
  {
    name: "Sonorama Ribera",
    city: "Aranda de Duero",
    province: "Burgos",
    subcategories: ["Indie", "Pop", "Rock"],
    official_url: "https://sonorama-aranda.com/",
  },
  {
    name: "Viña Rock",
    city: "Villarrobledo",
    province: "Albacete",
    subcategories: ["Rock", "Rap", "Punk", "Mestizaje", "Reggae"],
    official_url: "https://www.vina-rock.com/",
  },
  {
    name: "Azkena Rock Festival",
    city: "Vitoria-Gasteiz",
    province: "Álava",
    subcategories: ["Rock", "Hard Rock", "Garage", "Punk"],
    official_url: "https://www.azkenarockfestival.com/",
  },
  {
    name: "Mallorca Live Festival",
    city: "Calvià",
    province: "Illes Balears",
    subcategories: ["Indie", "Pop", "Rock", "Electrónica"],
    official_url: "https://mallorcalivefestival.com/",
  },
  {
    name: "O Son do Camiño",
    city: "Santiago de Compostela",
    province: "A Coruña",
    subcategories: ["Pop", "Rock", "Indie", "Urbana", "Electrónica"],
    official_url: "https://osondocamino.es/",
  },
  {
    name: "Río Babel",
    city: "Madrid",
    province: "Madrid",
    subcategories: ["Latina", "Indie", "Pop", "Urbana", "Rock"],
    official_url: "https://festivalriobabel.com/",
  },
  {
    name: "Rock Imperium Festival",
    city: "Cartagena",
    province: "Murcia",
    subcategories: ["Metal", "Hard Rock", "Heavy Metal"],
    official_url: "https://rockimperiumfestival.es/",
  },
  {
    name: "Leyendas del Rock",
    city: "Villena",
    province: "Alicante",
    subcategories: ["Metal", "Heavy Metal", "Hard Rock"],
    official_url: "https://www.leyendasdelrockfestival.com/",
  },
  {
    name: "Rototom Sunsplash",
    city: "Benicàssim",
    province: "Castellón",
    subcategories: ["Reggae", "Dub", "Dancehall", "World Music"],
    official_url: "https://rototomsunsplash.com/",
  },
  {
    name: "Medusa Festival",
    city: "Cullera",
    province: "Valencia",
    subcategories: ["Electrónica", "EDM", "Techno", "Hardstyle"],
    official_url: "https://medusasunbeach.com/",
  },
  {
    name: "Dreambeach",
    city: "Almería",
    province: "Almería",
    subcategories: ["Electrónica", "Techno", "EDM", "Drum and Bass"],
    official_url: "https://www.dreambeach.es/",
  },
  {
    name: "Monegros Desert Festival",
    city: "Fraga",
    province: "Huesca",
    subcategories: ["Electrónica", "Techno", "House", "Drum and Bass"],
    official_url: "https://monegrosfestival.com/",
  },
  {
    name: "Weekend Beach Festival",
    city: "Torre del Mar",
    province: "Málaga",
    subcategories: ["Urbana", "Rock", "Pop", "Electrónica", "Reggae"],
    official_url: "https://weekendbeach.es/",
  },
  {
    name: "Low Festival",
    city: "Benidorm",
    province: "Alicante",
    subcategories: ["Indie", "Alternative", "Pop", "Rock"],
    official_url: "https://lowfestival.es/",
  },
  {
    name: "VIDA Festival",
    city: "Vilanova i la Geltrú",
    province: "Barcelona",
    subcategories: ["Indie", "Alternative", "Pop"],
    official_url: "https://www.vidafestival.com/",
  },
  {
    name: "WARM UP Estrella de Levante",
    city: "Murcia",
    province: "Murcia",
    subcategories: ["Indie", "Pop", "Rock", "Electrónica"],
    official_url: "https://warmupfestival.es/",
  },
  {
    name: "Interestelar Sevilla",
    city: "Sevilla",
    province: "Sevilla",
    subcategories: ["Indie", "Pop", "Rock"],
    official_url: "https://interestelarsevilla.com/",
  },
  {
    name: "Festival de Les Arts",
    city: "Valencia",
    province: "Valencia",
    subcategories: ["Indie", "Pop", "Rock"],
    official_url: "https://festivaldelesarts.com/",
  },
  {
    name: "Granada Sound",
    city: "Granada",
    province: "Granada",
    subcategories: ["Indie", "Pop", "Rock"],
    official_url: "https://granadasound.com/",
  },
  {
    name: "SanSan Festival",
    city: "Benicàssim",
    province: "Castellón",
    subcategories: ["Indie", "Pop", "Rock"],
    official_url: "https://sansanfestival.com/",
  },
  {
    name: "Festival Gigante",
    city: "Guadalajara",
    province: "Guadalajara",
    subcategories: ["Indie", "Pop", "Rock"],
    official_url: "https://festivalgigante.com/",
  },
  {
    name: "CanelaParty",
    city: "Torremolinos",
    province: "Málaga",
    subcategories: ["Alternative", "Punk", "Indie", "Rock"],
    official_url: "https://canelaparty.com/",
  },
  {
    name: "Atlantic Fest",
    city: "Vilagarcía de Arousa",
    province: "Pontevedra",
    subcategories: ["Indie", "Pop", "Rock"],
    official_url: "https://atlanticfest.com/",
  },
  {
    name: "Morriña Fest",
    city: "A Coruña",
    province: "A Coruña",
    subcategories: ["Pop", "Urbana", "Latina"],
    official_url: "https://morrinafestival.com/",
  },
  {
    name: "PortAmérica",
    city: "Portas",
    province: "Pontevedra",
    subcategories: ["Indie", "Pop", "Rock", "Latina"],
    official_url: "https://portamerica.es/",
  },
  {
    name: "Festival de la Luz",
    city: "Boimorto",
    province: "A Coruña",
    subcategories: ["Pop", "Rock", "Indie", "Folk"],
    official_url: "https://festivaldelaluz.es/",
  },
  {
    name: "MUWI La Rioja Music Fest",
    city: "Logroño",
    province: "La Rioja",
    subcategories: ["Indie", "Pop", "Rock", "Electrónica"],
    official_url: "https://www.muwi.es/",
  },
  {
    name: "Cooltural Fest",
    city: "Almería",
    province: "Almería",
    subcategories: ["Indie", "Pop", "Rock"],
    official_url: "https://coolturalfest.com/",
  },
  {
    name: "Concert Music Festival",
    city: "Chiclana de la Frontera",
    province: "Cádiz",
    subcategories: ["Pop", "Rock", "Flamenco", "Latina"],
    official_url: "https://concertmusicfestival.com/",
  },
  {
    name: "Icónica Santalucía Sevilla Fest",
    city: "Sevilla",
    province: "Sevilla",
    subcategories: ["Pop", "Rock", "Flamenco", "Electrónica", "Latina"],
    official_url: "https://iconicafest.com/",
  },
  {
    name: "Noches del Botánico",
    city: "Madrid",
    province: "Madrid",
    subcategories: ["Pop", "Rock", "Jazz", "Soul", "World Music"],
    official_url: "https://nochesdelbotanico.com/",
  },
  {
    name: "Starlite Occident",
    city: "Marbella",
    province: "Málaga",
    subcategories: ["Pop", "Rock", "Latina", "Flamenco"],
    official_url: "https://starlitefestival.com/",
  },
  {
    name: "Pirineos Sur",
    city: "Lanuza",
    province: "Huesca",
    subcategories: ["World Music", "Folk", "Latina", "Pop"],
    official_url: "https://www.pirineos-sur.es/",
  },
  {
    name: "Festival Internacional do Mundo Celta de Ortigueira",
    city: "Ortigueira",
    province: "A Coruña",
    subcategories: ["Folk", "Celta", "World Music"],
    official_url: "https://festivaldeortigueira.com/",
  },
  {
    name: "Festival de la Guitarra de Córdoba",
    city: "Córdoba",
    province: "Córdoba",
    subcategories: ["Flamenco", "Jazz", "Rock", "Clásica"],
    official_url: "https://www.guitarracordoba.es/",
  },
  {
    name: "Jazzaldia",
    city: "San Sebastián",
    province: "Gipuzkoa",
    subcategories: ["Jazz", "Blues", "Soul"],
    official_url: "https://jazzaldia.eus/",
  },
  {
    name: "Getxo Jazz",
    city: "Getxo",
    province: "Bizkaia",
    subcategories: ["Jazz"],
    official_url: "https://www.getxo.eus/es/getxo-jazz",
  },
  {
    name: "Festival de Jazz de Vitoria-Gasteiz",
    city: "Vitoria-Gasteiz",
    province: "Álava",
    subcategories: ["Jazz", "Blues", "Soul"],
    official_url: "https://www.jazzvitoria.com/",
  },
  {
    name: "Eivissa Jazz",
    city: "Ibiza",
    province: "Illes Balears",
    subcategories: ["Jazz"],
    official_url: "https://eivissajazz.com/",
  },
  {
    name: "Jazz en la Costa",
    city: "Almuñécar",
    province: "Granada",
    subcategories: ["Jazz"],
    official_url: "https://jazzenlacosta.es/",
  },
  {
    name: "BluesCazorla",
    city: "Cazorla",
    province: "Jaén",
    subcategories: ["Blues", "Rock", "Soul"],
    official_url: "https://bluescazorla.com/",
  },
  {
    name: "Festival Internacional de Música y Danza de Granada",
    city: "Granada",
    province: "Granada",
    subcategories: ["Clásica", "Flamenco", "World Music"],
    official_url: "https://granadafestival.org/",
  },
  {
    name: "Cap Roig Festival",
    city: "Calella de Palafrugell",
    province: "Girona",
    subcategories: ["Pop", "Rock", "Latina"],
    official_url: "https://www.caproigfestival.com/",
  },
  {
    name: "ALMA Festival Barcelona",
    city: "Barcelona",
    province: "Barcelona",
    subcategories: ["Pop", "Rock", "Indie", "Soul"],
    official_url: "https://almafestival.info/barcelona/",
  },
  {
    name: "Guitar BCN",
    city: "Barcelona",
    province: "Barcelona",
    subcategories: ["Pop", "Rock", "Cantautor", "Flamenco"],
    official_url: "https://www.guitarbcN.com/",
  },
  {
    name: "Festival Mil·lenni",
    city: "Barcelona",
    province: "Barcelona",
    subcategories: ["Pop", "Rock", "Cantautor", "Jazz"],
    official_url: "https://www.festivalmillenni.com/",
  },
  {
    name: "Inverfest",
    city: "Madrid",
    province: "Madrid",
    subcategories: ["Indie", "Pop", "Rock", "Cantautor"],
    official_url: "https://inverfest.com/",
  },
  {
    name: "Vive Latino España",
    city: "Zaragoza",
    province: "Zaragoza",
    subcategories: ["Rock", "Latina", "Alternative", "Indie"],
    official_url: "https://www.vivelatino.es/",
  },
  {
    name: "Boombastic Asturias",
    city: "Llanera",
    province: "Asturias",
    subcategories: ["Urbana", "Pop", "Reggaetón", "Electrónica"],
    official_url: "https://boombasticfestival.com/",
  },
  {
    name: "Holika Festival",
    city: "Calahorra",
    province: "La Rioja",
    subcategories: ["Urbana", "Reggaetón", "Trap", "Latina"],
    official_url: "https://holikafestival.com/",
  },
  {
    name: "Puro Latino Fest Sevilla",
    city: "Sevilla",
    province: "Sevilla",
    subcategories: ["Urbana", "Reggaetón", "Latina", "Trap"],
    official_url: "https://purolatino.es/",
  },
  {
    name: "Cabo de Plata",
    city: "Barbate",
    province: "Cádiz",
    subcategories: ["Rock", "Rap", "Reggae", "Mestizaje"],
    official_url: "https://cabodeplata.com/",
  },
  {
    name: "Tsunami Xixón",
    city: "Gijón",
    province: "Asturias",
    subcategories: ["Punk", "Rock", "Hardcore", "Alternative"],
    official_url: "https://tsunamixixon.com/",
  },
  {
    name: "Z! Live Rock Fest",
    city: "Zamora",
    province: "Zamora",
    subcategories: ["Metal", "Heavy Metal", "Hard Rock"],
    official_url: "https://www.zliverock.com/",
  },
  {
    name: "Barcelona Rock Fest",
    city: "Santa Coloma de Gramenet",
    province: "Barcelona",
    subcategories: ["Metal", "Heavy Metal", "Hard Rock"],
    official_url: "https://barcelonarockfest.com/",
  },
  {
    name: "Sun and Thunder",
    city: "Fuengirola",
    province: "Málaga",
    subcategories: ["Metal", "Heavy Metal", "Hard Rock"],
    official_url: "https://sunandthunderfest.com/",
  },
  {
    name: "Rockin' Race Jamboree",
    city: "Torremolinos",
    province: "Málaga",
    subcategories: ["Rock and Roll", "Rockabilly", "Blues"],
    official_url: "https://www.rockinrace.com/",
  },
  {
    name: "Dantz Festival",
    city: "San Sebastián",
    province: "Gipuzkoa",
    subcategories: ["Electrónica", "Techno", "Experimental"],
    official_url: "https://dantz.eu/",
  },
  {
    name: "Huercasa Country Festival",
    city: "Riaza",
    province: "Segovia",
    subcategories: ["Country", "Americana", "Folk", "Rock"],
    official_url: "https://www.huercasacountryfestival.es/",
  },
  {
    name: "Rabolagartija",
    city: "Villena",
    province: "Alicante",
    subcategories: ["Rock", "Reggae", "Rap", "Mestizaje"],
    official_url: "https://rabolagartija.com/",
  },
  {
    name: "Love the 90's Festival",
    city: "Madrid",
    province: "Madrid",
    subcategories: ["Pop", "Dance", "Electrónica"],
    official_url: "https://lovethe90sfestival.com/",
  },
  {
    name: "Share Festival",
    city: "Barcelona",
    province: "Barcelona",
    subcategories: ["Urbana", "Pop", "Reggaetón", "Latina"],
    official_url: "https://sharefestival.org/",
  },
];

function slugify(value) {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/&/g, "y")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export const FESTIVALS = FESTIVAL_DATA.map((festival) => ({
  ...festival,

  pillar: "Culturales",
  pillar_slug: "culturales",

  category: "Festivales de música",
  category_slug: "festivales-de-musica",

  subcategory_slugs: festival.subcategories.map(slugify),

  watch_year: 2027,
  status: festival.status || "watching",
  enabled: true,
}));