/**
 * Municipios españoles con 30.000 habitantes o más.
 *
 * Referencia poblacional: 1 de enero de 2025.
 * Fuente base: INE, Cifras oficiales de población municipal.
 *
 * Se incluyen alias frecuentes/oficiales para reconocer nombres usados
 * por distintas webs, pero siempre se devuelve un nombre canónico.
 */

export const KNOWN_CITIES = [
  "Madrid",
  "Barcelona",
  "Valencia",
  "Zaragoza",
  "Sevilla",
  "Málaga",
  "Murcia",
  "Palma de Mallorca",
  "Las Palmas de Gran Canaria",
  "Alicante",
  "Bilbao",
  "Córdoba",
  "Valladolid",
  "Vigo",
  "Hospitalet de Llobregat",
  "Gijón",
  "Vitoria",
  "La Coruña",
  "Elche",
  "Granada",
  "Tarrasa",
  "Badalona",
  "Sabadell",
  "Oviedo",
  "Cartagena",
  "Móstoles",
  "Jerez de la Frontera",
  "Santa Cruz de Tenerife",
  "Pamplona",
  "Almería",
  "Alcalá de Henares",
  "Leganés",
  "Getafe",
  "Fuenlabrada",
  "San Sebastián",
  "Castellón de la Plana",
  "Burgos",
  "Alcorcón",
  "Santander",
  "Albacete",
  "San Cristóbal de La Laguna",
  "Marbella",
  "Logroño",
  "Badajoz",
  "Lérida",
  "Salamanca",
  "Tarragona",
  "Torrejón de Ardoz",
  "Huelva",
  "Dos Hermanas",
  "Parla",
  "Mataró",
  "Algeciras",
  "Santa Coloma de Gramanet",
  "León",
  "Alcobendas",
  "Jaén",
  "Reus",
  "Roquetas de Mar",
  "Cádiz",
  "Gerona",
  "Orense",
  "Telde",
  "Rivas-Vaciamadrid",
  "Baracaldo",
  "Santiago de Compostela",
  "Lugo",
  "Las Rozas de Madrid",
  "Lorca",
  "Torrevieja",
  "San Cugat del Vallés",
  "San Sebastián de los Reyes",
  "Cáceres",
  "Mijas",
  "San Fernando",
  "Guadalajara",
  "Cornellá de Llobregat",
  "El Ejido",
  "Torrente",
  "Chiclana de la Frontera",
  "El Puerto de Santa María",
  "Pozuelo de Alarcón",
  "Arona",
  "Toledo",
  "Melilla",
  "Vélez-Málaga",
  "Valdemoro",
  "San Baudilio de Llobregat",
  "Fuengirola",
  "Orihuela",
  "Talavera de la Reina",
  "Ceuta",
  "Pontevedra",
  "Gandía",
  "Rubí",
  "Manresa",
  "Coslada",
  "Estepona",
  "Santa Lucía de Tirajana",
  "Molina de Segura",
  "Benalmádena",
  "Alcalá de Guadaíra",
  "Palencia",
  "Benidorm",
  "Ciudad Real",
  "Paterna",
  "Guecho",
  "Avilés",
  "Majadahonda",
  "Sagunto",
  "Villanueva y Geltrú",
  "Torremolinos",
  "Arrecife",
  "Castelldefels",
  "Sanlúcar de Barrameda",
  "Viladecans",
  "Collado Villalba",
  "Boadilla del Monte",
  "El Prat de Llobregat",
  "Granollers",
  "La Línea de la Concepción",
  "Ferrol",
  "Irún",
  "Ponferrada",
  "Aranjuez",
  "Alcoy",
  "Arganda del Rey",
  "San Vicente del Raspeig",
  "Mérida",
  "Motril",
  "Zamora",
  "Ávila",
  "Granadilla de Abona",
  "Colmenar Viejo",
  "Sardañola del Vallés",
  "Pinto",
  "Linares",
  "Huesca",
  "Ibiza",
  "Elda",
  "Tres Cantos",
  "San Bartolomé de Tirajana",
  "Calviá",
  "Villarreal",
  "Cuenca",
  "Siero",
  "Mollet del Vallés",
  "Rincón de la Victoria",
  "Utrera",
  "Segovia",
  "Torrelavega",
  "Vic",
  "Adeje",
  "Figueras",
  "Manacor",
  "Gavá",
  "Alcira",
  "Esplugas de Llobregat",
  "Mairena del Aljarafe",
  "Denia",
  "Mislata",
  "San Feliu de Llobregat",
  "Santurce",
  "Puerto del Rosario",
  "Puertollano",
  "Alhaurín de la Torre",
  "Portugalete",
  "Alcantarilla",
  "Lucena",
  "Lloret de Mar",
  "Blanes",
  "Villafranca del Panadés",
  "Puerto Real",
  "La Orotava",
  "Santa Eulalia del Río",
  "Igualada",
  "Antequera",
  "Torre-Pacheco",
  "Burjasot",
  "Vendrell",
  "Soria",
  "La Rinconada",
  "Llucmajor",
  "Marrachí",
  "Basauri",
  "Plasencia",
  "Narón",
  "Ripollet",
  "Santa Pola",
  "Écija",
  "Olot",
  "Rentería",
  "San Adrián de Besós",
  "Arucas",
  "San Fernando de Henares",
  "Tudela",
  "Oleiros",
  "Los Palacios y Villafranca",
  "Langreo",
  "Arroyomolinos",
  "Don Benito",
  "Burriana",
  "Villagarcía de Arosa",
  "Los Realejos",
  "Águilas",
  "Moncada y Reixach",
  "Villajoyosa",
  "Tomelloso",
  "Cambrils",
  "Onteniente",
  "Galapagar",
  "Teruel",
  "Miranda de Ebro",
  "San Javier",
  "Yecla",
  "Mieres",
  "Inca",
  "Tortosa",
  "San Juan Despí",
  "Azuqueca de Henares",
  "Andújar",
  "Cieza",
  "Mazarrón",
  "San Roque",
  "Villena",
  "Aldaya",
  "Almendralejo",
  "Salt",
  "Arteijo",
  "Petrel",
  "Barberá del Vallés",
  "Aranda de Duero",
  "Agüimes",
  "Ronda",
  "Úbeda",
  "Castro-Urdiales",
  "Totana",
  "Navalcarnero",
  "Níjar",
  "Illescas",
  "Ames",
  "Ingenio",
  "Lejona",
  "San Pedro de Ribas",
  "Calafell",
  "Manises",
  "Sitges",
  "Ciudadela",
  "Vall de Uxó",
  "Carballo",
  "Chirivella",
  "Alcázar de San Juan",
  "Salou",
  "Campello",
  "Coria del Río",
  "Arcos de la Frontera",
  "Culleredo",
  "Puerto de la Cruz",
  "Játiva",
  "Crevillente",
  "Seseña",
  "Hellín",
  "Valdepeñas",
  "Mahón",
  "Jávea",
  "Catarroja",
  "Camargo",
  "Vinaroz",
  "Benicarló",
];

export const CITY_ALIASES = {
  "Palma": "Palma de Mallorca",
  "Palma de Mallorca": "Palma de Mallorca",
  "L'Hospitalet de Llobregat": "Hospitalet de Llobregat",
  "Hospitalet de Llobregat, L'": "Hospitalet de Llobregat",
  "Vitoria-Gasteiz": "Vitoria",
  "A Coruña": "La Coruña",
  "Coruña, A": "La Coruña",
  "Terrassa": "Tarrasa",
  "Donostia": "San Sebastián",
  "Donostia-San Sebastián": "San Sebastián",
  "Castelló de la Plana": "Castellón de la Plana",
  "Lleida": "Lérida",
  "Santa Coloma de Gramenet": "Santa Coloma de Gramanet",
  "Girona": "Gerona",
  "Ourense": "Orense",
  "Barakaldo": "Baracaldo",
  "Sant Cugat del Vallès": "San Cugat del Vallés",
  "Cornellà de Llobregat": "Cornellá de Llobregat",
  "Torrent": "Torrente",
  "Puerto de Santa María, El": "El Puerto de Santa María",
  "Sant Boi de Llobregat": "San Baudilio de Llobregat",
  "Gandia": "Gandía",
  "Getxo": "Guecho",
  "Sagunt": "Sagunto",
  "Vilanova i la Geltrú": "Villanueva y Geltrú",
  "Sant Vicent del Raspeig": "San Vicente del Raspeig",
  "Cerdanyola del Vallès": "Sardañola del Vallés",
  "Eivissa": "Ibiza",
  "Calvià": "Calviá",
  "Vila-real": "Villarreal",
  "Mollet del Vallès": "Mollet del Vallés",
  "Figueres": "Figueras",
  "Gavà": "Gavá",
  "Alzira": "Alcira",
  "Esplugues de Llobregat": "Esplugas de Llobregat",
  "Dénia": "Denia",
  "Sant Feliu de Llobregat": "San Feliu de Llobregat",
  "Santurtzi": "Santurce",
  "Vilafranca del Penedès": "Villafranca del Panadés",
  "Santa Eulària des Riu": "Santa Eulalia del Río",
  "Burjassot": "Burjasot",
  "El Vendrell": "Vendrell",
  "Marratxí": "Marrachí",
  "Errenteria": "Rentería",
  "Sant Adrià de Besòs": "San Adrián de Besós",
  "Vilagarcía de Arousa": "Villagarcía de Arosa",
  "Montcada i Reixac": "Moncada y Reixach",
  "La Vila Joiosa": "Villajoyosa",
  "Ontinyent": "Onteniente",
  "Sant Joan Despí": "San Juan Despí",
  "Aldaia": "Aldaya",
  "Arteixo": "Arteijo",
  "Petrer": "Petrel",
  "Barberà del Vallès": "Barberá del Vallés",
  "Leioa": "Lejona",
  "Sant Pere de Ribes": "San Pedro de Ribas",
  "Ciutadella de Menorca": "Ciudadela",
  "La Vall d'Uixó": "Vall de Uxó",
  "Xirivella": "Chirivella",
  "El Campello": "Campello",
  "Xàtiva": "Játiva",
  "Crevillent": "Crevillente",
  "Maó": "Mahón",
  "Xàbia": "Jávea",
  "Vinaròs": "Vinaroz",
};

export function getCanonicalCityName(value) {
  const cleaned = String(value || "").replace(/\s+/g, " ").trim();

  if (!cleaned) return null;

  return CITY_ALIASES[cleaned] || cleaned;
}

export const CITY_SEARCH_NAMES = Array.from(
  new Set([...KNOWN_CITIES, ...Object.keys(CITY_ALIASES)])
);
